@BFCD.Server_HostAddress = http://localhost:5253

GET {{BFCD.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BFCD.Server_HostAddress}}/customer/
Accept: application/json

###

GET {{BFCD.Server_HostAddress}}/SavingsAccount/
Accept: application/json

###